### ISSUE TITLE
Problems with the new Playground site on mobile

### ISSUE THREAD

**Issue by ironnysh** [WordPress/wporg-wasm#17]
I was browsing Playground’s lovely [new site](https://wordpress.org/playground/) on an iPhone SE, and noticed two issues:
1. The icons on the homepage are not the same size.
2. In “internal” pages ([see an example](https://wordpress.org/playground/development-environments/)), where breadcrumbs are visible, the top navigation bar creates an horizontal overflow.

See screenshots below (icons and overflow, respectively):
![IMG_1660](https://github.com/WordPress/wporg-wasm/assets/63248335/9334b3c5-ae99-42c9-9744-502556f9f70f)

![IMG_1661](https://github.com/WordPress/wporg-wasm/assets/63248335/2979bf35-14cf-44b9-a819-2d9a5de0a8a8)

**Comment by adamziel** [comment]
@jasmussen would you be able to help here?

**Comment by jasmussen** [comment]
Nice one, for the homepage I've fixed this.

For the secondary navigation bar, there's no easy fix here, for now it's "intentional" though I agree it's not ideal. I don't know how much we can do here, perhaps @adamwoodnz might know what's possible or not?

**Comment by adamwoodnz** [comment]
> I don't know how much we can do here, perhaps @adamwoodnz might know what's possible or not?

I think we can replace with our local nav block, I'll take a look.

**Comment by adamwoodnz** [comment]
I've swapped out the existing custom local nav for our local nav block used in sites across the network. There is a nav menu configured for this so you can easily update the menu items:

<img src="https://github.com/user-attachments/assets/0eac78ac-bbb4-4b2d-a21d-ce7c6810d79f" width="300">

## Screenshots

### Front page

| Desktop | Tablet | Mobile |
|-|-|-|
| ![wordpress org_playground_(5 1440x900)](https://github.com/user-attachments/assets/a43bae7b-2f32-4b9c-92a2-f1468eaabf43) | ![wordpress org_playground_(iPad)](https://github.com/user-attachments/assets/145ead4f-1cda-4024-91e9-4e1ca59a6a56) | ![wordpress org_playground_(Samsung Galaxy S20 Ultra)](https://github.com/user-attachments/assets/31149468-fcb7-4634-aa38-7db328de1808) |

### Page

| Desktop | Desktop Scrolled | Tablet | Mobile |
|-|-|-|-|
| ![wordpress org_playground_development-environments_(5 1440x900)](https://github.com/user-attachments/assets/1dd41590-e5d1-48b6-a8fb-da8e225a1a19) | ![wordpress org_playground_development-environments_(5 1440x900) (1)](https://github.com/user-attachments/assets/582ba986-d0c7-4f7c-a679-8cabada5a533) | ![wordpress org_playground_development-environments_(iPad)](https://github.com/user-attachments/assets/0433e37a-254b-4969-bbe4-ab9634f6f8b8) | ![wordpress org_playground_development-environments_(Samsung Galaxy S20 Ultra)](https://github.com/user-attachments/assets/ca97e7ba-e310-4c3f-83de-ba50c2eff14d) |
